Initial CWL Workflows
wtsi-hgi/arvados-pipelines pull request #3
Opened 2017-08-11 15:31 UTC by pkarnati2004

2017-08-14 09:41 UTC, jrandall requested changes
No changes to crunch_scripts

2017-08-14 11:18 UTC, jrandall requested changes
Remove commented lines throughout, move tests to `tests` subdirs and add scripts to run tests, rename CWL outputs so they are representative of what they are, ensure there is only one copy of each python script (may want to move Dockerfiles to facilitate this).

2017-08-14 11:18 UTC, jrandall commented on crunch_scripts/gatk-split-interval-list.py
> -    # try:
No commented out lines here

2017-08-14 11:18 UTC, jrandall commented on cwl/HaplotypeCaller.cwl
> +{
Not sure how we should handle HaplotypeCaller.cwl - maybe it would be better not to check it into the repo but rather to have a Makefile or script that fetches it from a release of the gatk conversion repo.

2017-08-14 11:18 UTC, jrandall commented on cwl/Haplotype_inputs.yml
> +analysis_type: HaplotypeCaller
This is effectively a test case - it should be in a tests subdirectory and the data it requires should be included and referenced by relative rather than absolute path.

2017-08-14 11:18 UTC, jrandall commented on cwl/inputs.cwl
> +analysis_type: HaplotypeCaller
I guess this is another test case - same as above - rename/move to subdir for tests and refer to test data by relative path

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/convert_docker/gatk-create-interval-lists.py
> +    # directory = os.path.join(os.getcwd(), basename)
git rid of these extra commented lines

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/convert_docker/gatk-create-interval-lists.py
> +class FileAccessError(Exception):
FileAccessError and APIError appear to be unused

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/convert_docker/gatk-create-interval-lists.py
> +#!/usr/bin/env python
should this be called dict_to_interval_list.py ?

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/convert_docker/gatk-create-interval-lists.py
> +    #parse the arguments from command line
git rid of unused old-style argument parsing code

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/convert_docker/gatk-create-interval-lists.py
> +    skip_sq_sn_regex = '_decoy$'
don't hard-code this - make it an input or don't use it at all

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/convert_first.cwl
> +# inputs:
eliminate commented lines

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/convert_first.cwl
> +  - id: out
name output something sensible such as "interval_list"

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/convert_first.cwl
> +# stdout: $(inputs.directory.split("/").slice(-1)[0].split(".").slice(0,-1).join("."))/$(inputs.dictionary.basename)
remove commented lines

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/inputs.yml
> +genome_chunks: 20
this seems like another test-case - move to tests subdir

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/scripts/gatk-create-interval-lists.py
> +#!/usr/bin/env python
there are two copies of this script, one in docker and one here - there should only be one.

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/scripts/gatk-split-interval-list.py
>  weight_seq = 120000
FileAccessError and APIError appear to be unused

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/scripts/gatk-split-interval-list.py
> +    # create new directory to store the split_interval_lists
remove commented lines

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/scripts/gatk-split-interval-list.py
> +        #change working directory
remove commented lines

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/scripts/gatk-split-interval-list.py
> +            # interval = "%s\t%s\t%s\t+\t%s\n" % (sn, start, end, "interval_%s_of_%s_%s" % (chunk_num, genome_chunks, str(target)[:str(target).index("_")]))
remove commented line

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/scripts/gatk-split-interval-list.py
> +    # genome_chunks = int(sys.argv[1])
remove commented lines

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/scripts/gatk-split-interval-list.py
> +    #change to working directory
remove commented lines

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/split_docker/gatk-split-interval-list.py
> -# import arvados      # Import the Arvados sdk module
remove commented line

2017-08-14 11:18 UTC, jrandall commented on crunch_scripts/gatk-split-interval-list.py
> -    # try:
no changes to files under crunch_scripts

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/split_docker/gatk-split-interval-list.py
>  #!/usr/bin/env python
duplicate file under docker and under the scripts directory - there should be only one

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/split_interval_first.cwl
> +cwlVersion: v1.0
rename this to something not involving "first" - probably `split_interval_list.cwl`

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/split_interval_first.cwl
> +  - id: outf
call output something more descriptive such as `interval_lists`

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/test.yml
> +dictionary:
this seems like a test - put in tests subdir?

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/workflow.cwl
> +# What is exactly the output of each files -- figure that out so that you can example out things and connect it
remove comment

2017-08-14 11:18 UTC, jrandall commented on cwl/workflow/convert_first.cwl
> +cwlVersion: v1.0
rename to something like `dict_to_interval_list.cwl` or `dict2interval_list.cwl`

2017-08-15 14:34 UTC, ThomasHickman commented on crunch_scripts/gatk-split-interval-list.py
> -    # try:
The diff here looks like it's wrong - in both wtsi-hgi's version (https://github.com/wtsi-hgi/arvados-pipelines/blob/master/crunch_scripts/gatk-split-interval-list.py#L42) and yejinyou's version (https://github.com/yejinyou/arvados-pipelines/blob/master/crunch_scripts/gatk-split-interval-list.py#L42), these files are uncommented.

2017-08-15 15:36 UTC, ThomasHickman commented
Cleaned up the python files and moved cwl files into their own folders

2017-08-17 15:52 UTC, merged